### ISSUE TITLE
Async requests?

### ISSUE THREAD

**Issue by hdimon** [tylerjensen/ServiceWire#10]
Hi,

Sorry that I'm writing this question here but this library has support for async/await usage? I mean if I can create contract with Task<> methods and it will be really async or not?

Thank you.

**Comment by tylerje** [comment]
@hdimon no, there is no support for such a thing in its current form. It's an interesting idea but I would probably recommend looking at my MessageWire project for asynchronous messaging between two processes if that is what you're after.

**Comment by tylerje** [comment]
@hdimon the code base now supports it. The NuGet package has not been updated. Thanks @vbondaryuk.
