### ISSUE TITLE
System.Security.Principal.IdentityNotMappedException on creating Named Pipe

### ISSUE THREAD

**Issue by RonaldZaZ** [tylerjensen/ServiceWire#11]
The problem is here
` _pipeSecurity.AddAccessRule(new PipeAccessRule(@"Everyone", PipeAccessRights.ReadWrite, AccessControlType.Allow));
`
Not every locale has the "Everyone" group. In other locale's it's named differently.
You should pass a security indentifier like this:
`SecurityIdentifier` everyone = new SecurityIdentifier(WellKnownSidType.WorldSid, null);
Then use that one instead of the "Everyone" string.

**Comment by tylerje** [comment]
@RonaldZaZ I've been crap for keeping up with my OSS projects. Thanks for the suggestion. I'm happy to take a PR if you need this before I can get to it.
