### ISSUE TITLE
Unable to find assembly in client via named pipes?

### ISSUE THREAD

**Issue by zedle** [tylerjensen/ServiceWire#14]
Hello, we've been trying to replace our custom named pipe implementation with ServiceWire but have been getting issues where we get errors such as:

`System.Runtime.Serialization.SerializationException: 'Unable to find assembly 'ServiceWireServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.'`

That was actually taken from a direct copy/paste of the sample code in the wiki for named pipes. We were getting the same issue with our actual project.

Are we doing something wrong? I'd really like to use this library as it cleans up the code so nicely. Thanks!

**Comment by tylerje** [comment]
What .NET framework or core version are you using? What version of the NuGet package are you using? Does one or both of your projects have the client framework selected?

**Comment by zedle** [comment]
.NET Framework 4.6.2, neither is Client Framework. v5.3.0 from NuGet.

**Comment by tylerje** [comment]
On second read, you appear to have a ServiceWireServer assembly defined. I'm assuming it contains the serialized type which ought to be in a shared common assembly rather that only in your server project. The client side needs access to those types you are serializing.

**Comment by zedle** [comment]
I have a shared project in place with the interface and serializable structs defined, both projects reference it.

**Comment by tylerje** [comment]
I'm happy to help via screen share using my Zoom account if you like. Send an email to me directly at tyler@tsjensen.com, if so, to arrange a time.

**Comment by tylerje** [comment]
Found the bug. Seems only to have popped up with output params. Fixed and published package version 5.3.1.

**Comment by zedle** [comment]
Awesome, I'll give it a shot right now.

**Comment by zedle** [comment]
Works great! Thanks again Tyler!
