### ISSUE TITLE
Topshelf incompatibility?

### ISSUE THREAD

**Issue by jgiacobbi** [tylerjensen/ServiceWire#15]
Hello, I'm getting the error : `'Cannot match method 'ReAuthenticate' to its server side equivalent'`

This worked prior to modifying the project to use topshelf. Are there any known issues here?

These are the relevant servicewire implementation details:

interface:
```
    public interface IAuthorize
    {
        bool IsAuthValid();
        bool ReAuthenticate(string authDomain, string username, string hashedPassword);
        AuthState GetAuthState();
    }
```

server:
```
    public class IpcAuthorize : IpcBase, IAuthorize
    {
        public bool ReAuthenticate(string AuthDomain, string Username, string HashedPassword)
        {
          ...
        }
    }
```

client:
```
        public static bool DoProxyAuth()
        {
            using (var client = GetClient<IAuthorize>())
            {
                return client.Proxy.ReAuthenticate(
                    string,
                    string,
                    string                );
            }
        }
```

**Comment by tylerje** [comment]
Is your AuthState class marked as [Serializable]?

**Comment by jgiacobbi** [comment]
Yes it is

**Comment by tylerje** [comment]
What version of the NuGet package are you using? Have you tried correcting the case of the params in your implementation to match the interface?

**Comment by jgiacobbi** [comment]
I'm using 5.3.1. I did try correcting the case, but it didn't help. I added a logger and got these two errors back.

```
[17:24:31 ERR] Error in ProcessRequest: 

System.IO.EndOfStreamException: Unable to read beyond the end of the stream.::   
	at System.IO.BinaryReader.FillBuffer(Int32 numBytes)::   
	at System.IO.BinaryReader.ReadInt32()::   
	at ServiceWire.Host.ProcessInvocation(ZkSession session, BinaryReader binReader, BinaryWriter binWriter, Stopwatch sw)::   
	at ServiceWire.Host.ProcessRequest(Stream readStream, Stream writeStream)

[17:24:31 ERR] ProcessClientThread error: 

System.IO.IOException: Pipe is broken.::   
	at System.IO.Pipes.PipeStream.CheckWriteOperations()::   
	at System.IO.Pipes.PipeStream.Flush()::   
	at System.IO.BufferedStream.Flush()::   
	at System.IO.BufferedStream.Dispose(Boolean disposing)::   
	at System.IO.Stream.Close()::   
	at System.IO.BinaryReader.Dispose(Boolean disposing)::   
	at ServiceWire.Host.ProcessRequest(Stream readStream, Stream writeStream)::   
	at ServiceWire.NamedPipes.NpListener.ProcessClientThread(NamedPipeServerStream pipeStream)
```

**Comment by jgiacobbi** [comment]
After trying everything it appears that my problem is that the server project was a Core project and not a Framework project. Frustrating, but ultimately good news.

**Comment by tylerje** [comment]
That sounds like a pipe is locked. Try changing the name of the pipe on both client and server and try again. If that doesn't work, I'm happy to spin up a Zoom session to help you figure it out. Send an email to tyler@tsjensen.com.

**Comment by tylerje** [comment]
@jgiacobbi I have not tried that with named pipes. I'll add that to my list of scenarios to test. Out of curiosity, which version of Framework and Core? Consider trying it with TCP on localhost 127.0.0,1.

**Comment by tylerje** [comment]
The problem almost undoubtedly comes in this file. https://github.com/tylerjensen/ServiceWire/blob/master/src/ServiceWire/NamedPipes/NpListener.cs

I'll have to do some experimentation to see if those differences are needed or if they can be dropped from the .NET 462 implementation. Or perhaps these can be made configurable.

**Comment by jgiacobbi** [comment]
Framework 4.6.2 and Core 2.2
