### ISSUE TITLE
User password hash authentication failed

### ISSUE THREAD

**Issue by nocanstillbb** [tylerjensen/ServiceWire#16]
1.serviceWire verson :4.0.1
2..net framework 4.0
3. exception info
=======================2019/6/13 11:58:31=======================
System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.IO.EndOfStreamException: 无法在流的结尾之外进行读取。
   在 System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   在 System.IO.BinaryReader.ReadInt32()
   在 ServiceWire.StreamingChannel.SyncInterface(Type serviceType, String username, String password) 位置 d:\Code\GitHub\ServiceWire\src\ServiceWire\StreamingChannel.cs:行号 104
   在 ServiceWire.TcpIp.TcpChannel.Initialize(String username, String password, Type serviceType, IPEndPoint endpoint, Int32 connectTimeoutMs) 位置 d:\Code\GitHub\ServiceWire\src\ServiceWire\TcpIp\TcpChannel.cs:行号 108
   在 ServiceWire.TcpIp.TcpChannel..ctor(Type serviceType, TcpZkEndPoint endpoint) 位置 d:\Code\GitHub\ServiceWire\src\ServiceWire\TcpIp\TcpChannel.cs:行号 38
   在 IWebRpcModelProxy..ctor(Type , TcpZkEndPoint )
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 ServiceWire.ProxyFactory.CreateProxy[TInterface](ProxyBuilder proxyBuilder, Object channelCtorValue) 位置 d:\Code\GitHub\ServiceWire\src\ServiceWire\ProxyFactory.cs:行号 53
   在 ServiceWire.ProxyFactory.CreateProxy[TInterface](Type channelType, Type ctorArgType, Object channelCtorValue) 位置 d:\Code\GitHub\ServiceWire\src\ServiceWire\ProxyFactory.cs:行号 35
   在 ServiceWire.TcpIp.TcpProxy.CreateProxy[TInterface](TcpZkEndPoint endpoint) 位置 d:\Code\GitHub\ServiceWire\src\ServiceWire\TcpIp\TcpProxy.cs:行号 9
   在 ServiceWire.TcpIp.TcpClient`1..ctor(TcpZkEndPoint endpoint) 位置 d:\Code\GitHub\ServiceWire\src\ServiceWire\TcpIp\TcpClient.cs:行号 19
   在 IOTMP.Operator.Client.SoketRpc.Client.WebClient..ctor(String ip, Int32 port, IntPtr webHwnd) 位置 F:\HaoYunProject\(11-1-1)MonitorClient - 备份\(11-1-1)MonitorClient\Main\IOTMP.Operator.Client\IOTMP.Operator.Client.SoketRpc\Client\WebClient.cs:行号 24
   在 IOTMP.Operator.Client.WebBrowser.MainWindow.<.ctor>b__3_0(Object <p0>, RoutedEventArgs <p1>) 位置 F:\HaoYunProject\(11-1-1)MonitorClient - 备份\(11-1-1)MonitorClient\Main\IOTMP.Operator.Client\IOTMP.Operator.Client.WebBrowser\MainWindow.xaml.cs:行号 55
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by nocanstillbb** [comment]
![image](https://user-images.githubusercontent.com/22405678/59403366-f4bb2780-8dd4-11e9-9bbc-349b33ea1b4d.png)
![image](https://user-images.githubusercontent.com/22405678/59403372-f8e74500-8dd4-11e9-8ab6-8f4cc0db6d11.png)

**Comment by nocanstillbb** [comment]
![1](https://user-images.githubusercontent.com/22405678/59403453-377cff80-8dd5-11e9-93d2-0c9f93830018.png)
![2](https://user-images.githubusercontent.com/22405678/59403460-39df5980-8dd5-11e9-87d4-31d0e9b9924c.png)

**Comment by tylerje** [comment]
Are you using .NET client profile? You are using a 5 year old version. Recommend you upgrade to the latest and min of .NET 4.62.

**Comment by nocanstillbb** [comment]
> Are you using .NET client profile? You are using a 5 year old version. Recommend you upgrade to the latest and min of .NET 4.62.

ok... thank you.
i using .net framework 4.0 .not .net framework 4.0 profile.
i have to use this .net framework verson.

**Comment by tylerje** [comment]
Can you email your project code to me? It's likely something simple but I'm not seeing it in your screen shots. tyler@tesjensen.com

**Comment by tylerje** [comment]
Another alternative is start with the simple reference or demo code and eliminate all other elements of your code. See if you can get it to work and then add until you find what the problem is.

**Comment by tylerje** [comment]
Fork the code and see if you can get it running in its current state but for a net40 target.

**Comment by nocanstillbb** [comment]
> 分叉代码并查看是否可以使其以当前状态运行，但是对于net40目标。

1.fork 
2.restore version which commit date is 2014/12/22
3. delete  project.assets.json
4. build and run
thank you

**Comment by tylerje** [comment]
I'm confused. Are you saying you got things working?

**Comment by nocanstillbb** [comment]
> I'm confused. Are you saying you got things working?

do thoes step.i get succuess communication

**Comment by nocanstillbb** [comment]
sorry ,my english so bad
i mine thank you very much
