### ISSUE TITLE
Any way for Bidirectional communication?

### ISSUE THREAD

**Issue by makotech222** [tylerjensen/ServiceWire#18]
I'm trying to upgrade a WCF application to use ServiceWire as a replacement. I have multiple uses of WCF DuplexClientBase, which allows the host to use a callback object.

Is there anything in ServiceWire to mimic this functionality?
Thanks!

**Comment by tylerje** [comment]
@makotech222 there is no provision in ServiceWire for duplex, callbacks or push. You may want to explore websockets via SignalR. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1

The only alternative, and I would not recommend this generally,  is polling. You could also explore the use of NetMQ for bi-directional communication. Have a look at https://github.com/tylerjensen/MessageWire

**Comment by makotech222** [comment]
Ah okay thank you. It looks like I will have to go the polling route for my use case. Its not performance intensive in any way, so it should be fine.

**Comment by tylerje** [comment]
@makotech222 that works. You can make the poll method very lightweight. The client keeps the socket open to the server until disposed, so the cost of polling on that connections will be small.

**Comment by makotech222** [comment]
@tylerje One last question I think. Looks like async/task based methods don't work? Calling client methods seems to be blocking, even when return type is Task. How should I poll if I'm blocked by the initial client call?

**Comment by tylerje** [comment]
@makotech222 it's working as designed. The Task return type is supported but remote execution is synchronous. See lines 256 to 277 in https://github.com/tylerjensen/ServiceWire/blob/master/src/ServiceWire/StreamingChannel.cs.

All execution of remote methods on the host occur on their own background thread. You can use the client on multiple threads and make multiple concurrent calls to the host. And while the interface you have in supported, the client does not return until a result is available. I need to document this behavior in an update to the main readme.

Meanwhile consider what async/await and the TPL do. It is impossible to share execution context across an RPC wire in ServiceWire. It is really a request/response mechanism. There would be no way for the Task returned to interrogate the context for a result without creating some kind of polling under the covers.

To execute polling, you will have to call the host at intervals, OR create a local method, passing it the client, and await the result of your long running method before returning the result. Then call that local method asynchronously. You will then be using the local synchronization context to wait for the result. The Task returned by your local method could be interrogated similarly as you are doing now but with the expected result. Meanwhile the client is able to execute other calls,the host executing those on other background threads.

**Comment by makotech222** [comment]
Thank you for the detailed response! I've changed my code to the following, but it seems like the host functions are still blocking (not being run on background thread?)

![image](https://user-images.githubusercontent.com/4389156/73615940-ce9bff00-45d2-11ea-8521-62b1e84c5e62.png)

**Comment by tylerje** [comment]
The TPL can only evaluate the Proxy and so may assume that the return will be immediate and therefore runs it synchronously. Try Factory.StartNew(..., TaskCreationOptions.LongRunning);

**Comment by makotech222** [comment]
Sorry I should clarify. The Task t is working properly, and doesn't get completed until after the 20 seconds. When I get to the client.Proxy.GetLog(), I get blocked until TryGetVal() finishes.

**Comment by tylerje** [comment]
Put a count on how many times you are calling GetLog. Then try switching to a TCP client and host. There may be something blocking while waiting for the result. I would like to know if it's behaving the same over TCP.

**Comment by tylerje** [comment]
Apologies. I mislead you. The Host can handle multiple calls across multiple connections. The client can only execute one operation at a time. For your approach to work, you would need two clients with independent connections. Look at NpListener.cs for example. I would not recommend this approach. I would make timed polling calls that return immediately telling me whether the server has something ready for me. Once it's ready, I would make the call to get that data. Tying up the client waiting for the server to be ready could be problematic, I think.

**Comment by makotech222** [comment]
I see. That is too bad. Thank you again for the help nonetheless! I will have to think of another solution for the bidirectional comms. Or perhaps refactor my code to work around it.

**Comment by makotech222** [comment]
For fun, tried this configuration.
Put Hosts on both sides, and the Server Host calls the client's host. Seems to work well with this limited test.

![image](https://user-images.githubusercontent.com/4389156/73616971-9f3fbf00-45df-11ea-844f-3fe251467f2d.png)

**Comment by tylerje** [comment]
That can be an excellent solution.
