### ISSUE TITLE
Crash when running on a 32-bit machine

### ISSUE THREAD

**Issue by tiagoad** [tylerjensen/ServiceWire#2]
When I make an RPC call, if the program is running on a 32-bit machine I get the following error:

```
jit compiler encountered an internal limitation
```

Is this problem known? Am I doing anything wrong?

Regards

**Comment by tylerje** [comment]
Try the latest NuGet package just published today. I'm uncertain if that will fix it mostly because I do not have a 32-bit machine on which to test.

**Comment by ByronAP** [comment]
this should be closed
