### ISSUE TITLE
Remove conditional compile flags for pipe security

### ISSUE THREAD

**Issue by sebcramer** [tylerjensen/ServiceWire#20]
Hello.

Cloud you remove the conditional compiles for pipe security (e.g. in `src/ServiceWire/NamedPipes/NpListener.cs`)? AFAIK all supported versions of .net should also support `PipeSecurity`.

Thanks.

**Comment by tylerje** [comment]
I'm happy to take a look at it. Feel free to submit a PR.

**Comment by sebcramer** [comment]
PR #22

**Comment by sebcramer** [comment]
I added another pull request using @Levi--G 's suggestion from issue #21 .

**Comment by tylerje** [comment]
Closing this issue. Not all versions support it. And I don't want to add a 3rd party library dependency to add it back into the NetStandard versions.
