### ISSUE TITLE
Expose PipeSecurity

### ISSUE THREAD

**Issue by sebcramer** [tylerjensen/ServiceWire#21]
Hello.

Feature request: could you expose PipeSecurity for modification?

Thanks.

**Comment by tylerje** [comment]
Please elaborate.

**Comment by sebcramer** [comment]
Right now it is not possible to modify the pipe's ACL settings. I (for one :-) ) would find it desirable to change the security settings of the named pipe. working on a PR right now.

**Comment by Levi--G** [comment]
I have just hit this issue too.
Did some research, read the PR, eventually found this:
https://github.com/HavenDV/H.Pipes/tree/master/NamedPipeServerStream.NetFrameworkVersion
Maybe you could use that to expose the pipesecurity?

**Comment by sebcramer** [comment]
I prepared a new pull request using @Levi--G 's idea (thanks!)

**Comment by Levi--G** [comment]
I forgot to submit mine 😅 
As long as it makes it to nuget i guess it doesn't matter. 😄 
I had it added to the constructor instead of on property but the result is the same.

**Comment by tylerje** [comment]
Let's make sure we have tests for all platforms. Apologies but I won't be able to review for at least a week.

**Comment by sebcramer** [comment]
I just had 5+ years of .NET abstinence. Someone needs to point me in the right direction. I am still marveling about the whole nuget thing. :-)

**Comment by Levi--G** [comment]
Well i was able to test this on .Net and .Net Core on windows, i do not have access to linux for a while and mac not at all. I didn't even know they had named pipes...

**Comment by sebcramer** [comment]
They do: Mono. I have access to Linux machines. I'll try my best. Regarding tests: I though @tylerje was talking about unit tests.

**Comment by Levi--G** [comment]
There are already unit tests and they all pass, the only tests that might need adding is one or two with the ACL's set. But you can look at the existing tests to add those. If you don't want to do it i can, it will just have to wait until i have time then. Maybe in 2 days.

**Comment by tylerje** [comment]
I don't want to add a 3rd party library dependency that adds something that was removed from NetStandard. The likelihood is that it would not work properly on Linux and that is likely why it was removed.
