### ISSUE TITLE
Permissions issue in 5.3.2

### ISSUE THREAD

**Issue by jgiacobbi** [tylerjensen/ServiceWire#23]
Hello,

We've been using ServiceWire with no issue for some time now. Our use case is a Framework 4.6.2 tray agent communicating over named pipe with a Framework 4.6.2 service. After upgrading from 5.3.1 to 5.3.2 suddenly the tray agent started crashing with no output. On a hunch I ran it as administrator and it worked normally. After reverting to 5.3.1 our vanilla install works as expected.

**Comment by tylerje** [comment]
In 5.3.2 we moved to .NET Standard 2.0 and 2.1 builds. There is a difference in the .NET 4.6.2 implementation of named pipes. To fix this error, we will need a specific .NET 4.6.2 build in the NuGet package. That make take a little time given current commitments, but the 5.3.1 package should work just fine for you.

**Comment by jgiacobbi** [comment]
Yeah 5.3.1 is working great for us for now. I guess we'll cross this bridge when we move to core. Thanks for the update.
