### ISSUE TITLE
Task support

### ISSUE THREAD

**Issue by Levi--G** [tylerjensen/ServiceWire#25]
Task<T> works just fine but when using a non-generic Task an error throws claiming VoidTaskResult is not marked as ISerializable. This only occurs when using an async Task:
```
Error in ProcessRequest: System.Runtime.Serialization.SerializationException: Type 'System.Threading.Tasks.VoidTaskResult' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.::   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(Type type)::   at System.Runtime.Serialization.FormatterServices.<>c.<GetSerializableMembers>b__5_0(MemberHolder mh)::   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)::   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)::   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()::   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)::   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)::   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)::   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)::   at ServiceWire.DefaultSerializer.Serialize(Object obj, String typeConfigName)::   at ServiceWire.ParameterTransferHelper.SendParameters(Boolean useCompression, Int32 compressionThreshold, BinaryWriter writer, Object[] parameters)::   at ServiceWire.Host.ProcessInvocation(ZkSession session, BinaryReader binReader, BinaryWriter binWriter, Stopwatch sw)::   at ServiceWire.Host.ProcessRequest(Stream readStream, Stream writeStream)
```

When returning Task.CompletedTask this works just fine. However that is rarely the case.

I have also noticed another issue, the tasks are not actually async but instead somehow wait synchronously on the result. On the client side i experience ui thread lag when periodically executing RPC's, when i wrap the synchronous call in Task.Run() it does work properly and does not hang.

**Comment by tylerje** [comment]
I need to update documentation because while the syntax of Task return type is supported, apparently it is not marked as Serializable. In fact async is not really supported. Under the covers the task type is stripped away over the wire and the method is executed on a worker thread on the server synchronously. 

The solution will require some research and time is limited. If you have a desire to contribute, I welcome PRs.

**Comment by WXWYK** [comment]
If I use await task ,when the task is completed,the client get error:Unable to read beyond the end of the stream.

**Comment by tylerje** [comment]
This is an RPC library. It doesn't properly support async/await. See my previous comment. I'm not convinced it makes sense to try to make it support a return type of Task or Task<T>.

**Comment by WXWYK** [comment]
Thank you for your reply. Asynchronous effect can be achieved in other ways, but use async/await is more concise.
