### ISSUE TITLE
InvokeMethod: Cannot match method due to string being in different corelib

### ISSUE THREAD

**Issue by xen2** [tylerjensen/ServiceWire#31]
I have one process in .NET FW and one in .NET Core.
I get an Exception in `InvokeMethod` due to type not matching:
`System.String, mscorlib` on one side and `System.String, System.Private.CoreLib` on the other side.

One possible fix is to alter `ToConfigName` to not append assembly name if it belongs to corelib (i.e. `t.Assembly == typeof(String).Assembly`).
Should I submit such a PR, or do you think another approach is better?

**Comment by tylerje** [comment]
Is this a single string parameter or return value? Or part of a more complex type? You could inject your own serializer. I'd prefer not to build in type translator logic in the library, but I do need to push a new package out that contains recent fixes to the serializer injection mechanism.

**Comment by xen2** [comment]
Those are parameters:
`RawShaderNavigationResult AnalyzeAndGoToDefinition(string projectPath, string sourceCode, RawSourceSpan span)`
I use a custom `ISerializer` but it's not being used for top-level parameter matching in `InvokeMethod`.
Here's where the equality happens:
https://github.com/tylerjensen/ServiceWire/blob/0a036c32515a034259621128814e711acd7cb647/src/ServiceWire/StreamingChannel.cs#L175

**Comment by tylerje** [comment]
Gotcha. I'm looking at it and wondering if there are other such cases. Perhaps we can resolve all such cases in one change. And since the ToConfigName extension is called just during startup, I don't mind adding something there.
