### ISSUE TITLE
not strongly named

### ISSUE THREAD

**Issue by kccarter76** [tylerjensen/ServiceWire#35]
Could not load file or assembly 'ServiceWire, Version=5.3.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

after giving it a strong name I get this exception:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Error Starting Transformation: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.Serialization.SerializationException: Unable to find assembly 'ServiceWire, Version=5.3.0.0, Culture=neutral, PublicKeyToken=04ff4e57e61e2a6f'.
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at ServiceWire.DefaultSerializer.Deserialize[T](Byte[] bytes)
   at ServiceWire.StreamingChannel.SyncInterface(Type serviceType, String username, String password)
   at ServiceWire.NamedPipes.NpChannel..ctor(Type serviceType, NpEndPoint npEndPoint, ISerializer serializer)
   at ITransformationRunFactoryServiceProxy..ctor(Type , NpEndPoint , ISerializer )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at ServiceWire.ProxyFactory.CreateProxy[TInterface](ProxyBuilder proxyBuilder, Object channelCtorValue, ISerializer serializer)
   at ServiceWire.ProxyFactory.CreateProxy[TInterface](Type channelType, Type ctorArgType, Object channelCtorValue, ISerializer serializer)
   at ServiceWire.NamedPipes.NpProxy.CreateProxy[TInterface](NpEndPoint npAddress, ISerializer serializer)
   at ServiceWire.NamedPipes.NpClient`1..ctor(NpEndPoint npAddress, ISerializer serializer)
   at SubSonic.Core.VisualStudio.Services.SubSonicTemplatingService.<GetTransformationRunFactoryAsync>d__104.MoveNext() in D:\Source\home\SubSonic.Core.VisualStudio\Services\SubSonicTemplatingService\TextTemplating.cs:line 480
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SubSonic.Core.VisualStudio.Services.SubSonicTemplatingService.<ProcessTemplateAsync>d__92.MoveNext() in D:\Source\home\SubSonic.Core.VisualStudio\Services\SubSonicTemplatingService\TextTemplating.cs:line 95	TemplateIntegrationTest	D:\Source\home\Integration\TemplateIntegrationTest\DAL\DataContext.stt	0	

```
public T Deserialize<T>(byte[] bytes)
        {
            if (null == bytes || bytes.Length == 0) return default(T);
            using (var ms = new MemoryStream(bytes))
            {
                return (T)_formatter.Deserialize(ms); <--- this is when the above exception is thrown
            }
        }
```

**Comment by tylerje** [comment]
ServiceWire is not a strong named package. You must be trying to use it in a project that requires it.

**Comment by kccarter76** [comment]
I have provided more information after signing the assembly, the exception is a head scratcher. since I can not find a reference to version 5.3.0.0 anywhere in the code base.

**Comment by tylerje** [comment]
5.3.0.0 is the binary serializer throwing the error. Can you share your interface code and data object code? And perhaps the code calling your Deserialize method?

**Comment by kccarter76** [comment]
if I can get this working to the point that the visual studio SDK is not required. I will push the contracts down to the Mono.TextTemplating project.

The host program

```
class Program
    {
        static void Main(string[] args)
        {
            var logger = new Logger(logLevel: LogLevel.Debug);
            var stats = new Stats();

            var pipename = TransformationRunFactory.TransformationRunFactoryService;

            TransformationRunFactoryService service = new TransformationRunFactoryService();

            using (NpHost host = new NpHost(pipename, logger, stats))
            {
                host.AddService<ITransformationRunFactoryService>(service);

                host.Open();

                while(service.IsRunning)
                {
                    Thread.Sleep(10);
                }
            }
        }
    }
```

server implemenation of the service
```
using Mono.VisualStudio.TextTemplating;
using Mono.VisualStudio.TextTemplating.VSHost;
using SubSonic.Core.VisualStudio.Host;
using System;
using System.Collections.Generic;


namespace SubSonic.Core.VisualStudio.HostProcess.Server
{
    public class TransformationRunFactoryService
        : ITransformationRunFactoryService
    {
        Dictionary<Guid, TransformationRunFactory> RunFactories = new Dictionary<Guid, TransformationRunFactory>();

        public bool IsRunning { get; protected set; } = true;

        public IProcessTransformationRunFactory GetTransformationRunFactory(Guid ID)
        {
            if (RunFactories.ContainsKey(ID))
            {
                return RunFactories[ID];
            }

            SubSonicTransformationRunFactory factory = new SubSonicTransformationRunFactory();

            RunFactories.Add(ID, factory);

            return factory;
        }

        public bool Shutdown()
        {
            return !(IsRunning = false);
        }
    }
}
```
service interface
```
namespace Mono.VisualStudio.TextTemplating.VSHost
{
	public interface ITransformationRunFactoryService
	{
		IProcessTransformationRunFactory GetTransformationRunFactory (Guid ID);
		/// <summary>
		/// Let the service now it can shutdown
		/// </summary>
		/// <returns></returns>
		bool Shutdown ();
	}
}
```
abstract classes
```
namespace Mono.VisualStudio.TextTemplating.VSHost
{
	public abstract class TransformationRunFactory
		: MarshalByRefObject
		, IProcessTransformationRunFactory
	{
		public const string TransformationRunFactoryService = "TransformationRunFactoryService";
		public const string TransformationRunFactoryMethod = "TransformationRunFactory";

		/// <summary>
		/// get the status of this instance.
		/// </summary>
		public bool IsAlive { get; set; }
		/// <summary>
		/// Create the transformation runner
		/// </summary>
		/// <param name="runnerType"></param>
		/// <param name="pt"></param>
		/// <param name="resolver"></param>
		/// <returns></returns>
		/// <remarks>
		/// abstracted, just because I am uncertain on how this would run on multiple platforms. Also visual studio classes may be required to pull of correctly.
		/// </remarks>
		public abstract IProcessTransformationRun CreateTransformationRun (Type runnerType, ParsedTemplate pt, ResolveEventHandler resolver);

		public abstract string RunTransformation (IProcessTransformationRun transformationRun);

		public override object InitializeLifetimeService ()
		{
			return null;
		}
	}
}
```
The Service Factory I am looking to return, have not implemented anything yet because I have been focused on getting a named pipe setup since MS does not have out of box remoting between frameworks.

```
namespace SubSonic.Core.VisualStudio.Host
{
    public class SubSonicTransformationRunFactory
        : TransformationRunFactory
        , IProcessTransformationRunFactory
    {
        public override IProcessTransformationRun CreateTransformationRun(Type runnerType, ParsedTemplate pt, ResolveEventHandler resolver)
        {
            throw new NotImplementedException();
        }

        public override string RunTransformation(IProcessTransformationRun transformationRun)
        {
            throw new NotImplementedException();
        }

        
    }
}
```

**Comment by kccarter76** [comment]
last but not least the service method that is instanciating the server and then connecting to it.

```
 private async ThreadingTasks.Task<IProcessTransformationRunFactory> GetTransformationRunFactoryAsync(TextWriter output, TextWriter error, CancellationToken cancellationToken)
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
        {
            if ((transformProcess == null) || (!RunFactoryIsAlive() || transformProcess.HasExited))
            {
                if (transformProcess != null && !transformProcess.HasExited)
                {
                    transformProcess.Kill();
                }

                string path = Path.Combine(
                        Path.GetDirectoryName(typeof(SubSonicCoreVisualStudioAsyncPackage).Assembly.Location),
                        "T4HostProcess",
                        SubSonicMenuCommands.SubSonicHostProcessFileName);

                if (!File.Exists(path))
                {
                    throw new FileNotFoundException(SubSonicCoreErrors.FileNotFound, SubSonicMenuCommands.SubSonicHostProcessFileName);
                }

                Guid guid = Guid.NewGuid();

                ProcessStartInfo psi = new ProcessStartInfo(path, guid.ToString())
                {
                    CreateNoWindow = true,
                    UseShellExecute = false,
                    RedirectStandardError = error != null,
                    RedirectStandardOutput = output != null
                };

                RuntimeInfo runtime = RuntimeInfo.GetRuntime(package.HostOptions.RuntimeKind);

                if (runtime.Kind == RuntimeKind.NetCore)
                {
                    psi.Arguments = $"\"{psi.FileName}\" {psi.Arguments}";
                    psi.FileName = Path.GetFullPath(Path.Combine(runtime.RuntimeDirectory, "..", "..", "..", "dotnet"));
                }

                try
                {
                    //_ = ProcessUtilities.StartProcess(psi, output, error, out System.Diagnostics.Process theT4Host, cancellationToken);

                    //transformProcess = theT4Host;
                }
                catch (Exception ex)
                {
                    await LogErrorAsync(ex.ToString(), new Location(TemplateFile));

                    return default;
                }

                npClient = new NpClient<ITransformationRunFactoryService>(new NpEndPoint(TransformationRunFactory.TransformationRunFactoryService));

                Stopwatch stopwatch = Stopwatch.StartNew();

                while (!cancellationToken.IsCancellationRequested)
                {
                    if ((this.runFactory != null) || (stopwatch.ElapsedMilliseconds >= 0x2710L))
                    {
                        stopwatch.Stop();
                        break;
                    }
                    Thread.Sleep(10);
                    try
                    {
#if !NETSTANDARD
                        runFactory = npClient.Proxy.GetTransformationRunFactory(guid);
                        //runFactory = (TransformationRunFactory)Activator.GetObject(typeof(TransformationRunFactory), $"ipc://TransformationRunFactoryService{guid}/TransformationRunFactory");
#else 
                        runFactory = ChannelServices.Connect<TransformationRunFactory>($"ipc://TransformationRunFactoryService{guid}/TransformationRunFactory");
#endif

                        if (!this.RunFactoryIsAlive())
                        {
                            this.runFactory = null;
                        }
                    }
                    catch (RemotingException)
                    {
                        this.runFactory = null;
                    }
                }

                if (stopwatch.IsRunning)
                {
                    stopwatch.Stop();
                }
            }

            return runFactory;
        }
```

**Comment by tylerje** [comment]
What frameworks do you have on both server and client end? You have a lot if other stuff going on here. I recommend you simplify and start with simple console apps on birth ends in the frameworks and platforms you want to use. Get communication working and then go back to your code to see if you can see what is causing the problem.

**Comment by kccarter76** [comment]
Visual studio is Net Framwork and the T4 Host Process is Net Core

**Comment by tylerje** [comment]
The binary serializer between the two is not always compatible. Try a simplified approach with just console apps in framework and core. Use an interface that passes the same types. If that works fine, you know you have something else going on. If not, try fingerprinting Guid to a string maybe. If neither work, you can inject your own serializer. I'm assuming you have the same ServiceWire library on both ends?

**Comment by kccarter76** [comment]
yes, there is a common netstandard 2.0 library between the two frameworks

**Comment by tylerje** [comment]
Yes, but each framework has its own binary serializer and there are some minor namespace differences.

**Comment by kccarter76** [comment]
hmm, so I need a net-standard binary serializer then?

**Comment by tylerje** [comment]
Not necessarily. Simplify first like I've suggested. If Guid won't serialize properly, try converting it to a string and back.

**Comment by kccarter76** [comment]
changed the Guid to string guidID and nothing changed.

**Comment by tylerje** [comment]
Did you write two simple console apps, one in .net core and one in framework, eliminating all the other code you have in your existing code?

**Comment by kccarter76** [comment]
I created a simple console app and it synchronized, but when I actually tried to return a transformationRunFactory instance I received the following:

Unable to read beyond the end of the stream.

**Comment by tylerje** [comment]
Is that class marked as Serializable? You call it an instance. Are you trying to return an object by ref to call methods on it remotely like an old remoting MarshalByRef object?

**Comment by tylerje** [comment]
Can you show the code of the two simple console apps?

**Comment by kccarter76** [comment]
the object to be returned is based of a MarshalByRef, I take it service wire does not care for that?

```
static void Main(string[] args)
        {
            using(var npClient = new NpClient<ITransformationRunFactoryService>(new NpEndPoint(TransformationRunFactory.TransformationRunFactoryService)))
            {
                var runFactory = npClient.Proxy.GetTransformationRunFactory(Guid.NewGuid().ToString());
            }
        }
```
```
static void Main(string[] args)
        {
            var logger = new Logger(logLevel: LogLevel.Debug);
            var stats = new Stats();

            var pipename = TransformationRunFactory.TransformationRunFactoryService;

            using (TransformationRunFactoryService service = new TransformationRunFactoryService())
            using (NpHost host = new NpHost(pipename, logger, stats))
            {
                host.AddService<ITransformationRunFactoryService>(service);

                host.Open();

                while(service.IsRunning)
                {
                    Thread.Sleep(10);
                }
            }
        }
```

**Comment by tylerje** [comment]
No. Definitely not. You don't really want that. A MarshallByRef object would be passed between application domain boundaries in the same process in order to call a method across that boundary. The ancient .NET Remoting enabled the same across processes. With ServiceWire, you don't need that. You use an interface and data transfer objects so that a client can call a server method as if it was local but it's not. Instead of trying to serialize a MarshallByRef object which I don't think is possible, just add methods to your interface to call from the client that will execute on the host server without trying to essentially serialize a remote executable object to achieve the same thing. It will be lighter, add a layer of abstraction away from you server implementation and you'll be in great shape. As a rule of thumb, never use a MarshallByRef unless you have to.

**Comment by tylerje** [comment]
Of course you won't have state like you might with a MarshallByRef object but you really don't want that in such an architecture.

**Comment by tylerje** [comment]
And don't use fields or properties in your interface. Remember ServiceWire is an RPC library.

**Comment by kccarter76** [comment]
I know app domain is going the way of the dodo with .net core and net 5 but that makes sense. I have compiled T4 template which I need the process host to execute and the result returned.

**Comment by kccarter76** [comment]
especially considering this, Type 'System.MarshalByRefObject' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.

**Comment by tylerje** [comment]
Good luck. I'm going to close this. Feel free to reach out if you need anything.
