### ISSUE TITLE
typeConfigName.ToType returns null in a framework client to netcore server

### ISSUE THREAD

**Issue by kccarter76** [tylerjensen/ServiceWire#36]
![image](https://user-images.githubusercontent.com/5841402/89721390-2f4d2f80-d99a-11ea-8fe0-5532b3264f0f.png)
![image](https://user-images.githubusercontent.com/5841402/89721566-50af1b00-d99c-11ea-9012-0a35dd14d756.png)

type is null but the object that was deserialized is already translated to the correct type, System.Private.Uri looks to be the netcore type configuration name instead of the framework type configuration name.

Type.GetType("System.Uri[], System.Private.Uri") | null 
obj.GetType().Assembly | {System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089} 
typeConfigName | System.Uri[], System.Private.Uri

if typeConfigName was set to "System.Uri[], System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". the type would not be null.

I wonder if this is the reason why you have not strong named service wire. but not having a strong name limits the library to applications that do not use strong names. would it break anything to return the object without converting if the type is null?

would this address the situation:
![image](https://user-images.githubusercontent.com/5841402/89721684-d4b5d280-d99d-11ea-950b-16f4902ff257.png)

**Comment by tylerje** [comment]
This has nothing to do with strong naming the assembly. It's entirely a side effect of trying to map types between frameworks when their namespaces have change. See the change in NetExtensions.cs which was an attempt to remedy this problem. Put a break point there and see if we're missing something with these types. It appears that the Uri type falls into this category but does not have the mscorelib in its .NET Framework type, yet still have a different assembly type for the Uri type, System vs System.Private. I'll have to set up a test for this and try to work it out. If you find the answer sooner, I'm happy to entertain a PR.

On the strong naming issue, this is the first time I've encountered anyone wanting it. Can you share your reasons for that?

**Comment by kccarter76** [comment]
of course, I am building a vsix solution for visual studio and it is a requirement that the assemblies pulled into visual studio are strong named. in fact, when I forgot to strong name my SubSonic.Core.Remoting assembly I had com errors left and right.

the project is to support T4 Templating where the template generator is interacting with netstandard assemblies and the T4 Generator that is stock with visual studio 2019 just does not support that.

**Comment by tylerje** [comment]
One option is to incorporate the code in your own project. Or fork it and strong name it. I'll see if I can get some cross framework tests up to find the issue with the Uri. Can you send me your interface, or a snippet of that contains that call?

**Comment by kccarter76** [comment]
the issue is that the assembly name in netcore is System.Private.Uri. I have some code in place and I going to open box test it. not sure how you have your current unit testing setup. I have not looked at that.

**Comment by tylerje** [comment]
Unit tests do not test across frameworks.

**Comment by kccarter76** [comment]
we don't need the unit test to test across framework. what we need is a type map that can use the full name of the type to map to the the type object desired. I am working on a TypeMapper for service wire.

**Comment by tylerje** [comment]
It's not the type that is the problem. It's the assembly name for that type. If we can find a list of types and hard code them, I'm okay with that since the type sync/mapping occurs only when the host or client is started.

**Comment by kccarter76** [comment]
no need to hard code the types. I have a solution and all we need to know is the assemblies that expose types in the system namespace.

**Comment by tylerje** [comment]
I want to find a way to do this without adding a dependency.

**Comment by kccarter76** [comment]
I can remove the nerd bank it's only a versioning tool

**Comment by kccarter76** [comment]
I have found another use case for the type mapper to have some configuration behind it. I will move as much as I can into a common library. but what will be syncing across the pipe will be a sub class of that type. The server will need to know about the base type so it can use polymorphism after deserialization.

**Comment by tylerje** [comment]
We're going down a rabbit hole for your use case and approach to RPC, so I'm going to recommend you made these changes on a fork and incorporate that code into your project. This effort, while interesting, is not really the direction I want to take ServiceWire. I hesitated on the original PR that just mapped mscorlib with System.Private.MsCoreLib.

**Comment by kccarter76** [comment]
I have thought about this last use case some more and I might have a work around that does not need the type mapper to be configurable. I am going to try that first. in regards mscorlib mapped with system.private. technically there not mapped together, there separated in different processes. Uri is the same object in both run-times, they just happen to be in different assemblies and Microsoft implemented more assemblies for netcore than they did framework.

**Comment by tylerje** [comment]
The mapping I'm referring to occurs here. https://github.com/tylerjensen/ServiceWire/blob/9f4053eb4ff693e79843570916164130878a652b/src/ServiceWire/NetExtensions.cs#L18

But I'm still not happy with that approach. I'm not liking the approach of actual mapping in the library either. We'll all be one big happy .NET 5 at some point, and .NET Framework will eventually end. I realize this is down the road, but I don't want to create a complex solution to a problem that is not common for users of the library.
