### ISSUE TITLE
If a RPC service returns an instantiated interface should methods on interface execute on the object created by the service.

### ISSUE THREAD

**Issue by kccarter76** [tylerjensen/ServiceWire#39]
I have a transformation run factory service that creates a run factory instance on the named pipe server. the return type of this method is an interface. When the run factory creates a transformation runner, its currently running the framework code in generating a runner on the client side. It should be creating the runner using the netcoreapp code on the server to create the runner. The execution of the runner must happen in the process for the named pipe service.

Is it possible for service wire to generate proxy for each method return type exposed by the service interface? I realize non interface types would be impossible to proxy if said method could not be overridden.

I realize the service interface will need functionality to dispatch the requests made against the objects created by the service, pretty sure service wire lacks that part.

Is my thinking flawed or is this a reasonable expectation on how a RPC service should work?

I have been thinking about this for two hours and this may not be a feature that service wire itself needs to implement. but the infrastructure to do this could sit on top of the named pipe and the service would expose the infrastructure to do this.

**Comment by tylerje** [comment]
That's a fairly packed question. Perhaps you can unpack it with some pseudo code? I'm honestly not understanding what you're asking.

From the ServiceWire perspective, it's rather simple. The client uses an interface in a shared assembly to dynamically create an assembly in memory that implements the interface. That implementation is only a means of communicating so the the host to pass parameters to the host and receive the response from the host.

The real implementation of the shared interface is on the host side, and it does not know anything about the client. This is the heart of any RPC model. 

I'm going to guess the meaning of your question, so feel free to correct me. It sounds as if you want a factory running on the host to return an interface to the client and the client would then dynamically produce a proxy for that interface and then the client would be able to call those methods. I'm assuming it's something like that.

Generally the use of a factory on the host side would be to use a specific implementation for a given interface/dependency based on some input from the client. If that is your goal, you can simply have a facade interface who's methods require the bit of data your host needs to determine which implementation on the host will be called. The facade implementation becomes your factory, so to speak. 

If you want your client to make a call to a factory on the host side and have it return an interface implementation like you would in a single process, then, yes, you're probably thinking of ServiceWire and RPC in the wrong way. The RPC equivalent to that would be what I described above given that the host in ServiceWire is designed to be stateless. It does not know who the client is unless you provide that information.

**Comment by kccarter76** [comment]
so if I am understanding what mentioned above. the service interface would look something like this.

```
public interface ITransformationRunFactoryService
        : IPipeServices
        , IProcessTransformationRunFactory
        , IProcessTransformationRunner
    {
        /// <summary>
        /// Starts up a transformation run factory
        /// </summary>
        /// <param name="id">id assigned to the run factory instance</param>
        /// <returns>rpc reference to a transformation run factory</returns>
        IProcessTransformationRunFactory TransformationRunFactory(Guid id);

        /// <summary>
        /// implements the ability to shutdown a local hosted service instance
        /// </summary>
        /// <param name="id">id assigned to the run factory instance</param>
        /// <returns>true, if successfull in shutting down the run factory.</returns>
        bool Shutdown(Guid id);
    }
```

instead of
```
    public interface ITransformationRunFactoryService
        : IPipeServices
    {
        /// <summary>
        /// Starts up a transformation run factory
        /// </summary>
        /// <param name="id">id assigned to the run factory instance</param>
        /// <returns>rpc reference to a transformation run factory</returns>
        IProcessTransformationRunFactory TransformationRunFactory(Guid id);

        /// <summary>
        /// implements the ability to shutdown a local hosted service instance
        /// </summary>
        /// <param name="id">id assigned to the run factory instance</param>
        /// <returns>true, if successfull in shutting down the run factory.</returns>
        bool Shutdown(Guid id);
    }

    [Serializable]
    public class TransformationRunFactoryService
        : BasePipeService
        , ITransformationRunFactoryService
        , IDisposable
    {
        private bool disposedValue;

        internal readonly static ConcurrentDictionary<Guid, IProcessTransformationRunFactory> runFactories = new ConcurrentDictionary<Guid, IProcessTransformationRunFactory>();

        public TransformationRunFactoryService(Uri serviceUri)
            : base(serviceUri) { }

        public IProcessTransformationRunFactory TransformationRunFactory(Guid id)
        {
            IProcessTransformationRunFactory factory = new Factory(id)
            {
                IsAlive = true
            };

            if (runFactories.TryAdd(id, factory))
            {
                return RemotingProxyFactory.Create<IProcessTransformationRunFactory>(GetType(), this).Consume(factory);
            }

            return default;
        }

        public bool Shutdown(Guid id)
        {
            if (runFactories.TryGetValue(id, out IProcessTransformationRunFactory factory))
            {
                foreach (var entry in Factory.Runners)
                {
                    if (entry.Value is TransformationRunner runner)
                    {
                        if (id == runner.Factory.ID)
                        {
                            factory.DisposeOfRunner(runner.RunnerId);
                        }
                    }
                }
            }

            return IsRunning = Factory.Runners.Count > 0;
        }
    }
```

**Comment by kccarter76** [comment]
okay I think I have got this. the only problem that I have at this point is that Type is not serializable. I will need to wrap that.

thank you for answering my question and the clarification that came with it.

interface
```
    public interface ITransformationRunFactoryService
        : IProcessTransformationRunFactory
        , IPipeServices
    {
        /// <summary>
        /// Get a transformation run factory
        /// </summary>
        /// <returns>rpc reference to a transformation run factory</returns>
        IProcessTransformationRunFactory TransformationRunFactory();

        /// <summary>
        /// implements the ability to shutdown a local hosted service instance
        /// </summary>
        /// <param name="id">id assigned to the run factory instance</param>
        /// <returns>true, if successfull in shutting down the run factory.</returns>
        bool Shutdown(Guid id);
    }
```
implementation
```
    [Serializable]
    public class TransformationRunFactoryService
        : BasePipeService
        , ITransformationRunFactoryService
        , IDisposable
    {
        private bool disposedValue;

        [NonSerialized]
        private IProcessTransformationRunFactory runFactory;

        public TransformationRunFactoryService(Uri serviceUri)
            : base(serviceUri) {
            runFactory ??= new Factory(Guid.NewGuid());
        }

        public Guid GetFactoryId()
        {
            return runFactory.GetFactoryId();
        }

        public bool IsRunFactoryAlive()
        {
            return runFactory.IsRunFactoryAlive();
        }

        public IProcessTransformationRunFactory TransformationRunFactory()
        {
            throw new InvalidOperationException(RemotingResources.MethodIsStubbedOutForProxyImpersonation);
        }

        public IProcessTransformationRunner CreateTransformationRunner(Type runnerType)
        {
            return runFactory.CreateTransformationRunner(runnerType);
        }

        public bool DisposeOfRunner(Guid runnerId)
        {
            return runFactory.DisposeOfRunner(runnerId); ;
        }

        public bool PrepareTransformation(Guid runnerId, ParsedTemplate pt, string content, ITextTemplatingEngineHost host, TemplateSettings settings)
        {
            return runFactory.PrepareTransformation(runnerId, pt, content, host, settings);
        }

        public string StartTransformation(Guid runnerId)
        {
            return runFactory.StartTransformation(runnerId);
        }

        public bool Shutdown(Guid id)
        {
            foreach (var entry in Factory.Runners)
            {
                if (entry.Value is TransformationRunner runner)
                {
                    if (id == runner.Factory.ID)
                    {
                        runFactory.DisposeOfRunner(runner.RunnerId);
                    }
                }
            }

            return IsRunning = Factory.Runners.Count > 0;
        }
    }
```

**Comment by tylerje** [comment]
Yes, the proxy on the client can be used again and again on the client side until you dispose it which disconnects it. I would recommend using a simple interface with just the RPC methods you need and data transfer objects that have no business logic in order to keep them lightweight since in many cases you can't or shouldn't execute that logic on the DTO on the wrong side of the wire. Good luck.
