### ISSUE TITLE
Socket exception on ubuntu box.

### ISSUE THREAD

**Issue by ersintarhan** [tylerjensen/ServiceWire#4]
Hello.
I tried ServiceWire on my ubuntu box as TcpHost with following code : 

>   var mytester = new MyTester();
>             var tcphost = new TcpHost(8090);
>             tcphost.AddService<IMyTester>(mytester);
>             tcphost.Open();
>             Console.WriteLine("Press Enter to stop the dual host test.");
>             Console.ReadLine();
>             tcphost.Close();
>             Console.WriteLine("Press Enter to quit.");
>             Console.ReadLine();

its works on windows perfect but on linux its throwing following exception : 

> > dotnet ServiceWireTest.dll
> > Unhandled Exception: System.Net.Sockets.SocketException: Operation not supported
> >    at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
> >    at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
> >    at ServiceWire.TcpIp.TcpHost.Initialize(IPEndPoint endpoint, ILog log, IStats stats, IZkRepository zkRepository)
> >    at ServiceWireServer.Program.Main(String[] args)
> > Aborted (core dumped)

**Comment by ByronAP** [comment]
same

```
Unhandled Exception: System.Net.Sockets.SocketException: Operation not supported
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at ServiceWire.TcpIp.TcpHost.Initialize(IPEndPoint endpoint, ILog log, IStats stats, IZkRepository zkRepository)
   at ATOM.GeneralServices.Program.Main(String[] args)
Aborted
```

**Comment by tylerje** [comment]
Fixed in latest commit. Will have a NuGet package out in the next few days.
