### ISSUE TITLE
Missing right lable “)” in Getting Started

### ISSUE THREAD

**Issue by JeremyWu917** [tylerjensen/ServiceWire#40]
Hi,

There is mistakes in [Getting Started](https://github.com/tylerjensen/ServiceWire/wiki/Getting-Started).
![2020-08-31_152028](https://user-images.githubusercontent.com/54832272/91693746-14876880-eb9e-11ea-8bd7-a8d0d83b5722.png)

**Comment by JeremyWu917** [comment]
Never mind.
I had fixed this issue.
Thanks

**Comment by tylerje** [comment]
Thanks for the edit. I've removed the commented line.
