### ISSUE TITLE
support IEnumerable<string> namedPipe

### ISSUE THREAD

**Issue by germagion** [tylerjensen/ServiceWire#47]
It seems that if I use in the interface IEnumerable<string> for named pipe I get an error: cannot match method to its server equivalent.

Ienumerable for non primitive types seems to work fine.

**Comment by tylerje** [comment]
Use an array. Remember it has to serialize the data, so an IEnumarable won't keep its enumerator state pointer over the wire. There's no advantage to using IEnumerable over the wire.

**Comment by germagion** [comment]
Thanks, I'll use array instead. As there is no advantage of IEnumerable over using an array I'll close the issue

**Comment by germagion** [comment]
Thanks, I'll use array instead. As there is no advantage of IEnumerable over using an array I'll close the issue
