### ISSUE TITLE
Support for nested types and deep APIs?

### ISSUE THREAD

**Issue by apkeno** [tylerjensen/ServiceWire#48]
I am considering moving some code to .NET 5/6 which means I can no longer use .NET Remoting. My application is a desktop C# app with a deep object oriented API with calls like:

var myApp = new App();
myApp.OpenFile("filename");
myApp.IntProperty = 5;
myApp.SubObject.StringProperty = "string";
IChild childObj = myApp.AddChild();
childObj.Name = "new child";

Working through the examples, I get an end of stream error when attempting to chain calls together. This worked in .NET Remoting. Is it possible to implement this syntax with ServiceWire?

**Comment by tylerje** [comment]
No. ServiceWire is not the same as .NET Removing. It is an RPC library that maps calls from a proxy through to a host of an instance. The client side proxy dies not have a reference to the concrete instance over the wire like you get in Remoting which is ultimately problematic for scale and network failures. I recommend you rearchitect your app as a disconnected client whether you use ServiceWire or not.
