### ISSUE TITLE
Idea to add Wire serializer in addition to Json.Net

### ISSUE THREAD

**Issue by snielsson** [tylerjensen/ServiceWire#5]
Hi

Just found ServiceWire lib and will give it a try. So far I have only skimmed the docs, but I noticed that Json.Net is used which is good. This also made me think, that it would be great to be able select other serializers, espcially high performance binary serializers. Here I am thinking of both Wire (https://rogeralsing.com/2016/08/16/wire-writing-one-of-the-fastest-net-serializers/) and of course Google Protocol buffers. Maybe I can make pull request later on, if I start using ServiceWire.

**Comment by guy-avery** [comment]
Did a quick experiment by changing the serialise / deserialise extension methods to use the Wire protocol - worked fine. Very simple change. Would require a little more work to allow developers to swap in and out their own serialisers.

**Comment by tylerje** [comment]
@snielsson this is an idea whose time is come. I'm working on making the serializer injectable. Stay tuned.

**Comment by tylerje** [comment]
@snielsson This has now been released in v5.3.0 just pushed to NuGet. Have a look at the unit tests that show how to do a Protobuf and a Newtonsoft.Json serializer. The new package reverts to BinaryFormatter for the default and loses the dependency on Newtonsoft.

**Comment by snielsson** [comment]
Cool and good to know, even though I am not currently using ServiceWire. I case you find it interesting, I have also stumbled upon this very fast MessagePack implementation https://github.com/neuecc/MessagePack-CSharp and also a very interesting related RPC-Web API Framework project called MagicOnion which combines MsgPack with Googles gRPC.
