### ISSUE TITLE
Getting "IOException: Pipe is broken" on new NpClient<TInterface>(new NpEndPoint(pipeName)) when running on a net6.0 ASP.NET Core app 

### ISSUE THREAD

**Issue by wouterroos** [tylerjensen/ServiceWire#52]
Hi @tylerje,

I'm getting the following exception when I try running a system using ServiceWire from an ASP,NET Core web application targetting `net6.0`:

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at ServiceWire.ProxyFactory.CreateProxy[TInterface](ProxyBuilder proxyBuilder, Object channelCtorValue, ISerializer serializer)
   at ServiceWire.ProxyFactory.CreateProxy[TInterface](Type channelType, Type ctorArgType, Object channelCtorValue, ISerializer serializer)
   at ServiceWire.NamedPipes.NpProxy.CreateProxy[TInterface](NpEndPoint npAddress, ISerializer serializer)
   at ServiceWire.NamedPipes.NpClient`1..ctor(NpEndPoint npAddress, ISerializer serializer)
   at MyProject.Remoting.ServiceWire.Common.V1.RequestSubmitter.CreateNpClient() in C:\Projects\MyProject\src\MyProject\Remoting\ServiceWire\Common\V1\RequestSubmitter.cs:line 116

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
IOException: Pipe is broken.
```

The exception is thrown when executing the following line of code:

`new NpClient<TInterface>(new NpEndPoint(pipeName))`

If I compile the exact same project against both `netcoreapp3.1` and `net48` everything works fine. It also works fine targetting `net6.0` if I run the system as a console application by changing the SDK in my `csproj` file from `Microsoft.NET.Sdk.Web` to `Microsoft.NET.Sdk`. I did some digging and found [this](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0#reduce-the-size-of-systemiopipelinespipe) in the ASP.NET Core 6.0 release notes, could this be relevant?

Do you have any idea if the change in ASP.NET Core I mentioned could be causing this issue and if so, if there is a way to get it to work?

Thanks!

**Comment by kaylumah** [comment]
This issue also occurs on `v5.4.0` of the ServiceWire package which was released in April.

Verified to be working on `Microsoft.NET.Sdk` and `Microsoft.NET.Sdk.Worker` but broken on `Microsoft.NET.Sdk,Web`

**Comment by tylerje** [comment]
@wouterroos what target framework is running your host?

**Comment by kaylumah** [comment]
If you mean which sdks Wouter has installed (discussed with him this afternoon)

.NET SDK (reflecting any global.json):
Version: 6.0.202
Commit: f8a55617d2

Runtime Environment:
OS Name: Windows
OS Version: 10.0.19044
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
Version: 6.0.4
Commit: be98e88c76

.NET SDKs installed:
2.1.818 [C:\Program Files\dotnet\sdk]
3.1.415 [C:\Program Files\dotnet\sdk]
6.0.100 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by tylerje** [comment]
Just curious about the .NET runtime version of the host process. Based on the OP, the client is an ASP.NET app running on .NET 6. There has to be a host app. What's it running on?

**Comment by wouterroos** [comment]
@tylerje The host is a ASP.NET app net6.0 console app running a [generic host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-6.0) to run a service. We use ServiceWire to communicate with other services with the same set-up, either in-proc or in separate processes. As mentioned above we've narrowed the issue down to the combination of `net6.0` and `Microsoft.NET.Sdk.Web`. See below for combinations we've verified to be working:

- `net48` - `Microsoft.NET.Sdk`
- `netcoreapp3.1` - `Microsoft.NET.Sdk`
- `net6.0` - `Microsoft.NET.Sdk`
- `net48` - `Microsoft.NET.Sdk.Web`
- `netcoreapp3.1` - `Microsoft.NET.Sdk.Web`

**Comment by tylerje** [comment]
@wouterroos it's hard to imagine how adding to web sdk would alter named pipes behavior. Would you be willing to experiment by switching to TCP without changing your runtime targets and SDKs? This may help us isolate it to named pipes. If we also get an error under TCP, we will want to examine the interface to see if the proxy IL generation is not supporting something in the interface.

**Comment by wouterroos** [comment]
@tylerje I agree it’s weird but it is what where seeing. We’ve replicated the issue on multiple machines to make sure it’s not a configuration issue. I’ll do the TCP test asap and will let you know once I have the results.

**Comment by wouterroos** [comment]
@tylerje I just ran a test using TCP, again I'm seeing that all combinations **except** `net6.0` and `Microsoft.NET.Sdk.Web` work perfectly fine. See below for the error I got:

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at ServiceWire.ProxyFactory.CreateProxy[TInterface](ProxyBuilder proxyBuilder, Object channelCtorValue, ISerializer serializer)
   at ServiceWire.ProxyFactory.CreateProxy[TInterface](Type channelType, Type ctorArgType, Object channelCtorValue, ISerializer serializer)
   at ServiceWire.TcpIp.TcpProxy.CreateProxy[TInterface](TcpEndPoint endpoint, ISerializer serializer)
   at ServiceWire.TcpIp.TcpClient`1..ctor(TcpEndPoint endpoint, ISerializer serializer)
   at Copper.Remoting.ServiceWire.Common.V1.RequestSubmitter.CreateNpClient() in C:\Projects\Copper2\src\Copper\Remoting\ServiceWire\Common\V1\RequestSubmitter.cs:line 117

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
EndOfStreamException: Unable to read beyond the end of the stream.
```

**Comment by tylerje** [comment]
Well, there's a clue. It's not pipes or tcp then but the mechanism for exchanging Metadata for the interface and generating the dynamic proxy. I'll review this week.

**Comment by tylerje** [comment]
@wouterroos are you using a custom serializer or the default serializer?

**Comment by tylerje** [comment]
@wouterroos please check out the PR. I believe the error in the client is due to an error in serializing ServiceSyncInfo on the host side when the StreamingChannel asks for it and expects to read an int in response. I'm wondering if you can create a local build and test in your scenario to see if this resolves the issue by giving you a better error on the client side. My thinking is that the default binary serialization between the two different runtime SDK libraries is to blame, the binary serializer throwing an error. It's a theory and I don't have a good way to test it on my end.

**Comment by wouterroos** [comment]
@tylerje I referenced the ServiceWire project from the PR in our solution and ran the scenario again. Please see the results below.

```
System.NotSupportedException
  HResult=0x80131515
  Message=BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
  Source=System.Runtime.Serialization.Formatters
  StackTrace:
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at ServiceWire.DefaultSerializer.Serialize[T](T obj) in C:\Projects\ServiceWire\src\ServiceWire\DefaultSerializer.cs:line 17

```

As for the question about serialization, please see below for how we use ServiceWire on both the client and the service side (in this scenario both are running in the same process, same SDK etc. and I'm using TCP). Here ServiceWire serves as the technology stack underneath a genering 'Remoting' library, hence the use of generics and interfaces. `IMethodRequest` and `IMethodResponse` have a single `string` property that contains all the information we need to process the request on the other side.

Service
```csharp
_npHost = new TcpHost(new IPEndPoint(IPAddress.Parse(_requestReceiverSettings.IPAddress), _requestReceiverSettings.Port));
_npHost.AddService<IConsumer<IMethodRequest, IMethodResponse>>(new RemotingDispatcher<TContract>(instance, _dispatchMessageFormatter));
_npHost.Open();
```

Client
```csharp
using var npClient = new TcpClient<IConsumer<IMethodRequest, IMethodResponse>>(new TcpEndPoint(new IPEndPoint(IPAddress.Parse(_requestSubmitterSettings.IPAddress), _requestSubmitterSettings.Port)));
var response = await npClient.Proxy.Consume(new ConsumeContext<IMethodRequest> { Message = methodRequest }).ConfigureAwait(false);
var responseObject = _clientMessageFormatter.DeserializeReply(methodInfo.DeclaringType, methodInfo, response.Message);
```

**Comment by kaylumah** [comment]
Reading [binaryformatter](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/binaryformatter-serialization-obsolete) has been marked obsolete in `.NET5`  We never targeted it (since it is not LTS) but I can imagine dat `net5.0` and `Microsoft.NET.Sdk.Web` combination is also broken

**Comment by wouterroos** [comment]
@tylerje I've reverted our solution back to NamedPipes and I'm getting the same results as I mentioned above (as expected). When I set the `EnableUnsafeBinaryFormatterSerialization` property to `true` in the `net6.0` ASP.NET project (as mentioned in the article @kaylumah mentioned) everything works as expected, but this is obviously not a good solution. 

Going from the article, It seems the solution would be to implement a new `ISerializer` that doesn't rely on `BinaryFormatter`. If you agree, please let me know if this is something that can be implemented in ServiceWire short-term (I don't see any other implementations of `ISerializer` in the current codebase) or if we need to implement something ourselves. 

Anyway, thanks for helping us figuring out what is the problem, this helps us a lot!

**Comment by tylerje** [comment]
@wouterroos thanks for helping me figure this out. I will be pushing the fix to master and publishing a new NuGet package along with some documentation in the readme about the limitation under an ASP.NET app and using the enable flag in the project file. Using a different default serializer would slow it down. The rationale behind preventing its use in a web application is clear, but at least they have acknowledged that there may be cases where it makes sense and thus the feature switch.

**Comment by tylerje** [comment]
Version 5.4.1 with the bug fix and readme updated published.

**Comment by tylerje** [comment]
@wouterroos the newest package, version 5.5.0, no longer uses BinaryFormatter. That should allow you to drop the project exception flag.

**Comment by wouterroos** [comment]
@tylerje Thanks, will give it a try soon!
