### ISSUE TITLE
Is it possible to use this library in a two-way fashion?

### ISSUE THREAD

**Issue by brandonhood** [tylerjensen/ServiceWire#60]
The implementation suggests that the pipe is duplex, but the documentation suggests that the API is one-way. Is it possible for two clients to talk to each other (without resorting to something like polling) or would it require a second pipe?

**Comment by tylerje** [comment]
@brandonhood can you share an example of code as to how you would take advantage of this? The pipes connection is duplex but keep in mind that the library supports the same RPC interactions over named pipes as it does TCP. It does not try to be a SignalR replacement that allows the server to send unsolicited messages to the client.

You're using named pipes, so presumably you're on the same machine. There is no reason your host cannot also have a client connection to the first client which is also a host.
