### ISSUE TITLE
Byref Enums

### ISSUE THREAD

**Issue by berk-csi** [tylerjensen/ServiceWire#62]
When I try to use an enumeration passed as a reference in my interface with ServiceWire, I am getting the following exception:

`"Non-primitive native types (e.g. Decimal and Guid) ByRef are not supported."`

A simple interface like below can be used as a reproducer:
```
    public enum eTest
    {
        OK,
        NoGood
    }

    public interface ITest
    {
        void Test(ref eTest aTest);
    }
```

Now, since (most) enumerations are simple integers, I was wondering if it would be possible to allow ByRef enums by casting the enum to an integer before sending it out to the client and casting it back to the original enum after client returns from the call?

I have multiple interfaces with ByRef enums, and I'd love to be able to use ServiceWire with them without changing the argument list (and breaking compatibility). I tried adding `[Serializable]` attribute to the enum but it didn't help.

Any help is appreciated.

**Comment by tylerje** [comment]
The error occurs in the IL proxy generator for the client. I don't recall the reason for the limitation. It will require some experimentation.

**Comment by berk-csi** [comment]
Hi @tylerje,

I was wondering if you had a chance to look into the byref enums issue as described above. We've already migrated our libraries (from WCF) to ServiceWire and it's working great (thanks!). However, several of our products can't yet be migrated to ServiceWire (hence are stuck at using .NET Remoting) due to having byref enums on their public interfaces. It would be awesome to be able to use ServiceWire for all our IPC needs.

Any help/guidance is appreciated.

**Comment by tylerje** [comment]
@berk-csi sorry, no. I've not had time to address this. I'm buried in other projects and won't be able to get to this any time soon. I welcome a PR if you figure it out.

**Comment by berk-csi** [comment]
Hi @tylerje,

I think I have something that works: [https://github.com/tylerjensen/ServiceWire/pull/68](). I also added tests for the newly supported ByRef Enumerations, but I am not sure if I covered all the bases.

This is my first attempt at contributing to an open-source project on GitHub, so please let me know if I skipped a step.

**Comment by tylerje** [comment]
@berk-csi please let me know if the new package is working for you as desired and thanks again for your contribution.

**Comment by berk-csi** [comment]
It working great so far! Thanks again for this awesome library and letting me contribute to it!

Berk


From: Tyler Jensen ***@***.***>
Date: Saturday, December 3, 2022 at 9:02 PM
To: tylerjensen/ServiceWire ***@***.***>
Cc: Berk Taftali ***@***.***>, Mention ***@***.***>
Subject: Re: [tylerjensen/ServiceWire] Byref Enums (Issue #62)

@berk-csi<https://github.com/berk-csi> please let me know if the new package is working for you as desired and thanks again for your contribution.
