### ISSUE TITLE
TcpClient is failing to create instance in .net framework 6

### ISSUE THREAD

**Issue by NandishNR** [tylerjensen/ServiceWire#63]
Getting exception as "SyncInterface failed: Type or version of type unknown". It's in .net framework and it's packages are directly added from nuget. However, same code is working in .net core and it's packages are directly added from nuget.

**Comment by tylerje** [comment]
Can we clarify?

You are referencing a .NET Framework (version?) package in a .NET 6 app and trying to use an interface defined in that package in TcpClient?

Is that a correct reading of your inquiry? If not, please clarify.

Do you own and build the package?

Is it a public package?

Can you share the interface code?

**Comment by kondareddy** [comment]
![Screenshot 2022-08-25 044052](https://user-images.githubusercontent.com/1445374/186539381-c67f8c68-08cb-4d5c-9a1a-8bf47fa7921a.png)

To be clear on the issue.
When we tried adding ServiceWire reference on .NET 4.6.2 and .NET Core Project - both got 5.5.1. Implementation wise same on both projects at our end. perfectly works on .NET Core project but fails on .NET 4.6.2 project with below error.

![Screenshot 2022-08-25 044052](https://user-images.githubusercontent.com/1445374/186539847-384d0d4a-d7bd-4454-a655-71976b803505.png)
**stack trace**
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ServiceWire.ProxyFactory.CreateProxy[TInterface](ProxyBuilder proxyBuilder, Object channelCtorValue, ISerializer serializer, ICompressor compressor)
   at ServiceWire.ProxyFactory.CreateProxy[TInterface](Type channelType, Type ctorArgType, Object channelCtorValue, ISerializer serializer, ICompressor compressor)
   at ServiceWire.TcpIp.TcpProxy.CreateProxy[TInterface](TcpZkEndPoint endpoint, ISerializer serializer, ICompressor compressor)
   at ServiceWire.TcpIp.TcpClient`1..ctor(TcpZkEndPoint endpoint, ISerializer serializer, ICompressor compressor)
   at JioMeet.Common.InterProcess.AppInstanceClientWire.Initialize(String ipAddress, Int32 port)

**Comment by tylerje** [comment]
Can you share the code for your interface?

**Comment by kondareddy** [comment]
Thanks Tylerje.

Downgrading to package to 5.3.4 issue fixed.

Actually we have old app in .NET 4.6.2 and new app built on .NET 6 with WinUI3.0 , we want to have communication between these two, will that work?

**Comment by tylerje** [comment]
If you're willing to share the interface with me, as I've asked, I would be happy to run some tests to find the problem.

**Comment by KingRikkie** [comment]
@tylerje 
Same issue here on Linux and .NET 6. Downgrading to 5.3.4 did not fix the issue, crashes as soon as you try to connect on client. This is a my entire interface
```cs
public interface IIPCBridge
{
    List<float> GetData();
}
```
Client:
```cs
var ipcBridgeClient = new NpClient<IIPCBridge>(new NpEndPoint("tester-pipe"));
var response = ipcBridgeClient.Proxy.GetData();
foreach (var data in response)
{
    Console.WriteLine(data);
}
```
Host: 
```cs
public class IPCBridge : IIPCBridge
{
    public IPCBridge() { }
    public List<float> GetData()
    {
        List<float> list = new();
        list.Add(99.625F);
        return list;
    }
}
.
.
.
static void Main(string[] args)
{
    var logger = new Logger(logLevel: LogLevel.Debug);
    var stats = new Stats();
    var ipcBridge = new IPCBridge();
    var nphost = new NpHost("tester-pipe", logger, stats);
    nphost.AddService<IIPCBridge>(ipcBridge);
    nphost.Open();
    .
    .
    .
     nphost.Close();
}
```

**Comment by KingRikkie** [comment]
Exact same happens with the TCP connection. 
```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeAccessException: SyncInterface failed. Type or version of type unknown.
   at ServiceWire.StreamingChannel.SyncInterface(Type serviceType, String username, String password)
   at ServiceWire.TcpIp.TcpChannel.Initialize(String username, String password, Type serviceType, IPEndPoint endpoint, Int32 connectTimeoutMs)
   at ServiceWire.TcpIp.TcpChannel..ctor(Type serviceType, IPEndPoint endpoint, ISerializer serializer, ICompressor compressor)
   at IIPCBridgeProxy..ctor(Type , IPEndPoint , ISerializer , ICompressor )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at ServiceWire.ProxyFactory.CreateProxy[TInterface](ProxyBuilder proxyBuilder, Object channelCtorValue, ISerializer serializer, ICompressor compressor)
   at ServiceWire.ProxyFactory.CreateProxy[TInterface](Type channelType, Type ctorArgType, Object channelCtorValue, ISerializer serializer, ICompressor compressor)
   at ServiceWire.TcpIp.TcpProxy.CreateProxy[TInterface](IPEndPoint endpoint, ISerializer serializer, ICompressor compressor)
   at ServiceWire.TcpIp.TcpClient`1..ctor(IPEndPoint endpoint, ISerializer serializer, ICompressor compressor)```

**Comment by tylerje** [comment]
@KingRikkie this appears to be a difference in how the types are noted in the initial handshaking. I'll have to set up some tests to determine what the problem is. Thanks for the info today. It may take some time to get a solution out given my current availability.

**Comment by tylerje** [comment]
@KingRikkie I'm unable to reproduce the problem. Clone and pull and run DemoHost and DemoClient on Windows. DemoHost will run using .NET 6 and DemoClient .NET Framework 4.6.2. The code runs fine. Compare the demo implementation with your code and let me know what's different. I'm only trying on TCP as the code that syncs the interfaces does not depend on the channel type. I'm curious to know what you find.

**Comment by tylerje** [comment]
This is the commit that tests your case. https://github.com/tylerjensen/ServiceWire/commit/c4a2f5350443baee6f834bc7938f5fc73848f5a7

**Comment by KingRikkie** [comment]
@tylerje I copied them into 2 new .NET 6.0 applications on Linux and the same error still happens on the client. I don't have a Windows machine atm.
[DemoClient](https://gist.github.com/KingRikkie/521366afc4d13b7e5808aa0252e76962)
[DemoHost](https://gist.github.com/KingRikkie/8092430e21c734a7952458b43245bfb2)

**Comment by tylerje** [comment]
I'll try on Linux then.

**Comment by tylerje** [comment]
@KingRikkie -- wait. You copied them into 2 new .NET 6.0 applications? How so? I build them in Linux and run them fine but have to remove the netcoreapp3.1 target as the code ```List<float> list = new();``` does not compile for that target. So I'm thinking there's more to this story than meets the eye. If we can find a time, I'd be happy to jump on a Zoom call to try to help.

**Comment by tylerje** [comment]
@KingRikkie can you do a ```dotnet --version``` and ```dotnet --list-sdks``` and post the result here from your Linux environment? Here's mine:

```
tyler@Legion:~/ServiceWire/src$ dotnet --version
7.0.100-rc.1.22431.12

tyler@Legion:~/ServiceWire/src$ dotnet --list-sdks
3.1.423 [/usr/share/dotnet/sdk]
6.0.401 [/usr/share/dotnet/sdk]
7.0.100-rc.1.22431.12 [/usr/share/dotnet/sdk]
```

**Comment by KingRikkie** [comment]
> @KingRikkie -- wait. You copied them into 2 new .NET 6.0 applications? How so? I build them in Linux and run them fine but have to remove the netcoreapp3.1 target as the code `List<float> list = new();` does not compile for that target. So I'm thinking there's more to this story than meets the eye. If we can find a time, I'd be happy to jump on a Zoom call to try to help.

I only copied the contents of the 2 Program.cs, not the csproj. 
```
dotnet new console -n DemoClient
cd DemoClient
dotnet add package ServiceWire
```
Then copy over the source from what I've linked. Nothing special. 
```
$ dotnet --version
6.0.109
$ dotnet --list-sdks
6.0.109 [/usr/share/dotnet/sdk]
```

**Comment by tylerje** [comment]
Try updating your SDK. I'm not finding 6.0.109 in the release notes, so I have to assume something is wrong on your end. https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by KingRikkie** [comment]
> Try updating your SDK. I'm not finding 6.0.109 in the release notes, so I have to assume something is wrong on your end. https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Updated to 6.0.110, still same error.

**Comment by tylerje** [comment]
@KingRikkie can you zip up your whole solution and drop it here? The copy of the demo client in which you are still getting the error? I'll try it on my machine. But before you do that, try updating to SDK 6.0.402.

**Comment by KingRikkie** [comment]
[Demo.zip](https://github.com/tylerjensen/ServiceWire/files/9964101/Demo.zip)
I can not upgrade to 6.0.4 as it is not available for Manjaro yet.

**Comment by KingRikkie** [comment]
> @KingRikkie can you zip up your whole solution and drop it here? The copy of the demo client in which you are still getting the error? I'll try it on my machine. But before you do that, try updating to SDK 6.0.402.
@tylerje 
I've updated to .NET 7 now and the error still happens even on freshly built Host/Client. There is definitely something wrong on Linux.

**Comment by tylerje** [comment]
@KingRikkie it's something to do with the projects. Yours don't work in my environment. Mine do. But I haven't has time to figure out why.

**Comment by KingRikkie** [comment]
@tylerje All I did was create a new console app through dotnet, add ServiceWire nuget package, copy over your example source.
