### ISSUE TITLE
Manage exception in defaultserializer (Json)

### ISSUE THREAD

**Issue by fabricefou** [tylerjensen/ServiceWire#69]
Hi,
Exception are not managed by system.text.JSON serializer. 
So if exception is thrown on client side, exception is lost.
Maybe we should add an exceptionConverter class that implement JsonConvertor<Exception> to manage exception.

**Comment by tylerje** [comment]
@fabricefou please provide an example with code.

**Comment by fabricefou** [comment]
More information and exemple here

https://github.com/dotnet/runtime/issues/43026#issuecomment-705904399

Need to implement Read function.
I can do it later if needed.

**Comment by tylerje** [comment]
@fabricefou if you want to write that in the default serializer and submit a PR, I'm happy to take a look. If you do, please be sure to include tests.

**Comment by tylerje** [comment]
Will not address this at this time.
