### ISSUE TITLE
Can I use this repo to intercept RPC calls?

### ISSUE THREAD

**Issue by zydjohnHotmail** [tylerjensen/ServiceWire#72]
Hello:
I found this repo, I want to know if I can use it to intercept some RPC calls.  One example use case is that for some custom wallet, which uses RPC to get blanance from a blockchain RPC server.  But it is not easy to find the RPC server IP address, or URL.
I can find the localhost port number used by wallet, which is a browser extension, like MetaMask but for BTC like tokens.
If it is possible, give me an idea on how to proceed, what information is necessary, I can get localhost PORT, may be user name & password, but no other information, I want to use this repo to find other information like: RPC server IP, port number, etc.
Thanks,

**Comment by tylerje** [comment]
@zydjohnHotmail thanks for the question. What you're talking about is generally referred to a service discovery. ServiceWire does not support discovery. You would need to write your own discovery service or use an open source solution.

https://devopscube.com/open-source-service-discovery/

ServiceWire assumes you know. It does have an interceptor proxy but that wouldn't be what you're talking about. You could have a middleware service that knows about other services, takes registrations and exit or unavailability polls, and provides that information to your client. That would be a simplistic discovery service.
