### ISSUE TITLE
Does ServiceWire support events?

### ISSUE THREAD

**Issue by codecat** [tylerjensen/ServiceWire#73]
I really like the ServiceWire API, and would love to use it. The only thing I'm not sure if it fully supports, is something like Events. Something a client can subscribe to receive notifications from the server. Is this supported, or would I have to create 2 pipes to do this?

**Comment by tylerje** [comment]
@codecat there is no support for events, per se. As you point out, you would need a second pipe with the client as host. This is a common challenge in distributed RPC systems. ServiceWire does not attempt to provide a solution for this.
