### ISSUE TITLE
Calls to the proxy in a WinUI application using NamedPipe client & BinaryFormatterSerializer fail.

### ISSUE THREAD

**Issue by berk-csi** [tylerjensen/ServiceWire#74]
I am trying to use ServiceWire (NamedPipe & BinaryFormatterSerializer) with a WinUI based desktop application targeting .NET 6. I can successfully start the service, but any calls to the proxy made from the WinUI app is failing in SyncInterface method:

![image](https://user-images.githubusercontent.com/101315025/231129354-352567c4-fc68-443b-980d-e26ce7420ca7.png)

Calls to the proxy work if I don't use BinaryFormatterSerializer, or if I change the application to use WinForms rather than WinUI as the UI framework.

Attached reproducer solution has the latest ServiceWire projects along with two clients: one WinUI based and the other WinForms based. They share the code referencing ServiceWire (based on the published [named pipes example](https://github.com/tylerjensen/ServiceWire/wiki/Services-Over-Named-Pipes)) via a shared C# project. When using the default serializer, both applications can use ServiceWire without any errors. When using BinaryFormatterSerializer, only the WinForms application works.

Any help with resolving this issue is deeply appreciated!

Berk

[ServiceWire.WinUI.zip](https://github.com/tylerjensen/ServiceWire/files/11199335/ServiceWire.WinUI.zip)

**Comment by tylerje** [comment]
The binary formatter between versions of .NET and operating systems is not guaranteed to be compatible. The WinUI formatter is likely different in some way that cannot be resolved. I recommend abandoning the binary formatter.
