### ISSUE TITLE
Connection timeout is not working while creating TcpClient against suspended process

### ISSUE THREAD

**Issue by NandishNR** [tylerjensen/ServiceWire#75]
TcpClient is used from ServiceWire.TcpIp library in our project to communicate between the processes to know the application instance is running already.

**_tcpClient = new TcpClient<IAppInstanceMessaging>(_tcpZkEndPoint);** is working for fresh instance/second instance is launched on existence of first instance (**Not suspended state**).

**_It fails_**, in case first instance is in **suspended state** and trying to run another instance. Problem is, execution will not come out from this line of code and no connection timeout error as well for any duration.

Default timeout is 2500ms and tried for different numbers as well.

**Comment by tylerje** [comment]
Can you provide the code? I'm not following your explanation. Connection timeout is not the same as completing a secure connection. In your case, why are you using a secure connection with the handshake overhead? I have many other questions that only your code will answer.

**Comment by NandishNR** [comment]
![image](https://user-images.githubusercontent.com/47853879/234474797-55c58f41-c7ff-490c-a333-3e0d9957678e.png)

Above is the code snippet. I have application with above code, where one instance in suspended state was in release mode and running 2nd instance through debug mode.

Where execution comes to **_tcpClient = new TcpClient(_tcpZkEndPoint);** it won't come out/no exception as well.

**Comment by kondareddy** [comment]
One of the use case to avoid duplicate instances lunched. Recently we started getting issues like not able to lunch the app. When we checked, When ever app process goes into suspended state we are not able to check instance is running or not? it gets struck in initialization always. Our understanding/expectation is that time-out should help us here.
![image](https://user-images.githubusercontent.com/1445374/234479568-f320e88c-e784-4f42-901b-c081745527c5.png).

we still need to find why process got suspended, for now at least we want users to relaunch to continue using the app.

**Comment by tylerje** [comment]
It appears you are assigning a new instance of client without disposing the previous instance. I would not recommend reusing the client object. Since I don't see exactly what you're doing with the client, including whether you're properly disposing it, I'm left to guess.

**Comment by kondareddy** [comment]
Use Cases
1. App Instance 1 - launched - when this code executed - we get remote connection failed hence we will launch new instance 
2. When attempted to launch app Instance 2 - when this code executed - we get response, we do come checks like version number if newer, we close instance 1 and launch instance 2 else we close instance 2 and bring instance 1 to foreground.

Above all works in normal scenario's. But lets assume instance process went into suspended state then we don't get any response while trying to launch instance 2. if we can get time-out working we ca handle this issue.

FYI - each client object is process specific,

**Comment by tylerje** [comment]
When you say App Instance, are you referring to client or host or both? I'm a little confused by your description. Is all of this happening on the same machine? Can you elaborate using the terms client and host rather than app instance which is unclear for me?

**Comment by kondareddy** [comment]
during app launch we always check by trying to connect to host with client object - if we failed to create client then we start host assuming that this is the first app instance.

in case app process (where host was also running) goes into suspended state-  this check gets struck never give response.

if still not clear - we will create sample and share steps to reproduce!!

**Comment by kondareddy** [comment]
App is WPF desktop, host is running as part of desktop app. When desktop app/process goes into suspended state we are unable to handle?

FYI - host also running in same machine.

**Comment by tylerje** [comment]
If they're on the same machine, how is the WPF host in suspended state while the client is not? Is the client running as a Windows Service that cannot be suspended?

And if these are on the same machine, why not use Named Pipes and not bother with connection security? This would reduce overhead dramatically. 

The question of connecting to a sleeping/suspended WPF app may better be answered without ServiceWire and just access the Windows processes directly.

Starting a new process of the same app that is in suspension/sleep is probably not a good idea. I think you need to rethink this solution.

**Comment by tylerje** [comment]
I'm assuming you found a way around this.
