### ISSUE TITLE
Any chance of Json RPC support over ServiceWire?

### ISSUE THREAD

**Issue by DamianReeves** [tylerjensen/ServiceWire#8]
You wouldn't need to implement the JsonRpc bits as this repo does it for you [Microsoftvs-streamjsonrpc](/https://github.com/Microsoft/vs-streamjsonrpc).

I like ServiceWire and the named pipes support but JsonRpc would make it much more portable and accessible to non .NET clients.

Great library!

**Comment by tylerje** [comment]
No plans to support JsonRpc. Perhaps in the future. I'm happy to take a look at a PR that does the trick.
