### ISSUE TITLE
"SyncInterface failed. Type or version of type unknown." In the streamingchannel

### ISSUE THREAD

**Issue by gervisc** [tylerjensen/ServiceWire#84]
I am very happy with the nuget package ServiceWire. But since version 5.5.2 I am getting the error "SyncInterface failed. Type or version of type unknown."  
It's probably related to the change in StreamingChannel.cs.

I use the the nuget package directly in my project it works fine, but if I pack this in project in a private nuget package and use this private package in a different project, it doesn't work and I get the error "SyncInterface failed. Type or version of type unknown."

**Comment by tylerje** [comment]
Are your client and server running on different .NET versions? (Framework vs Core?)

**Comment by gervisc** [comment]
yes the client is using .net 6.0 and the server is net48.  And there is a common project with shared classes which is compiled too both net48 and .net 6.0. These three packages are then packed as nuget packages and i used in another solution.

**Comment by tylerje** [comment]
That's the problem.

**Comment by tylerje** [comment]
The types in your sync is likely hanging up on types that changed between those versions. Can you post your interface?

**Comment by gervisc** [comment]
I actually changed the interface.    I tried cleaning and rebuilding everything. And then when I downgraded service it worked.  Is it cached?  Did i needed to restart the pc, after i changed the interface?

**Comment by tylerje** [comment]
It is not cached beyond the instance.

**Comment by gervisc** [comment]
I'll do some research on monday, I think it is related to a change in the interface and not which version of serviceWire i am using. 
Thanks for the help, I missed the fact that I changed the interface, and your question helped me finding that out.

**Comment by tylerje** [comment]
Closing.

**Comment by tylerje** [comment]
No changes planned.
