### ISSUE TITLE
Getting TypeLoadException in client.

### ISSUE THREAD

**Issue by Su-s** [tylerjensen/ServiceWire#85]
![image](https://github.com/tylerjensen/ServiceWire/assets/37269911/e318ac28-0b3b-4f7c-b4e0-05919fc14873)

Hi please help to resolve the issue with the client using namedpipes. 

```

public interface IHostServices
{
    IDiagnosticsService Diagnostics { get; init; }
    IAppBackgroundService AppBackgroundService { get; init; }
}

public class HostServices : IHostServices
{
    public HostServices(IDiagnosticsService diagnostics, IAppBackgroundService appBackgroundService)
    {
        Diagnostics = diagnostics;
        AppBackgroundService = appBackgroundService;
    }

    public IDiagnosticsService Diagnostics { get; init; }
    public IAppBackgroundService AppBackgroundService { get; init; }
}
```

this is my hostservice. the server is starting, but the exception is occurring while starting the client.

I've tried updating the client properties **from {get;init;} to {get;set;}** after reading some **StackOverflow** answers. but I got another issue which is **targetinvocation exception** in client

**Comment by tylerje** [comment]
Looks like you're trying to host two services in one. Separate them or combine the. ServiceWire was not designed to support service composition like you're expecting. It won't return an instance to the client. It's not like the old .NET remoting. It creates a proxy on the client side to pass method calls to the host.

**Comment by Su-s** [comment]
i didn't get that. could you please explain a bit more and help me to resolve the issue?

**Comment by tylerje** [comment]
Study the demo code here. 

https://github.com/tylerjensen/ServiceWire/blob/master/src/Demo/DemoCommon/Contracts.cs

**Comment by tylerje** [comment]
If you keep it simple, it will work.
