### ISSUE TITLE
Error handling best practices

### ISSUE THREAD

**Issue by bugproof** [tylerjensen/ServiceWire#87]
How to throw exceptions or return more detailed error messages? I guess I need to make `Result` class as part of my contract?

I'm using your library to create a proxy for .NET framework 4.7.2 library that doesn't work with modern .NET runtime. So I am able to call it from .NET 8. The only issue is I don't know how to forward exceptions/errors to the client.

For now if exception occurs on the host side on the client I get `EndOfStreamException`

**Comment by tylerje** [comment]
Catch and log the exception on the host side and return a value in your result that indicates an exception occurred. Exception objects with stack trace are expensive to serialize and the serialization of those objects from one framework to another is not likely to be supported anyway.

**Comment by bugproof** [comment]
So `Result` type as I thought. Thank you.
