### ISSUE TITLE
Error passing System.Uri between .NET 4.6.2 and .NET 8

### ISSUE THREAD

**Issue by Leon99** [tylerjensen/ServiceWire#92]
Just passing an instance of System.Uri between .NET 4.6.2 and .NET 8 processes gives this:
```
System.InvalidCastException: Object must implement IConvertible.
   at ServiceWire.Aspects.InterceptChannel.InvokeMethod(String metaData, Object[] parameters)
```
We found a possible reference to this issue in https://github.com/SubSonic-Core/SubSonic.Core.ServiceWire 

> implements additional typemapping so System.Uri can be mapped between framework and netcore runtimes

but that's an outdated fork, and it's unclear why that fix hasn't been merged here in 4 years.
Any ideas much appreciated.

**Comment by tylerje** [comment]
Is there a reason you don't want to just use a string? Much faster. No type
serialization difference. The other option is a custom serializer.

**Comment by tylerje** [comment]
https://github.com/tylerjensen/ServiceWire/blob/fad14780853d5b51aa4896b900cb20aa297b0bac/src/Tests/Unit/ServiceWireTests/NpTests.cs#L51

Have a look at this test.

https://github.com/tylerjensen/ServiceWire/blob/fad14780853d5b51aa4896b900cb20aa297b0bac/src/ServiceWire/Channel.cs#L16

And how the default serializer is used if one is not specified.

https://github.com/tylerjensen/ServiceWire/blob/fad14780853d5b51aa4896b900cb20aa297b0bac/src/ServiceWire/DefaultSerializer.cs#L7

Make a copy of the default. Alter as you like, including different handling
for a Uri type. And that should give you what you need.

**Comment by tylerje** [comment]
Of course, you will need to inject your custom serializer in the client and host constructors. Test your serializer between the two runtimes, and Bob's your uncle.

**Comment by tylerje** [comment]
The reason I don't burden the default serializer with multiple type revolvers between multiple runtimes is there are far too many combinations and that would bloat the default to cover rare edge cases.
